version: '1.1'

services:
  app:
    build: .
    ports:
      - "8084:8080"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=${API_BASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"