name: SeasonsBot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t seasonsbot:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag seasonsbot:latest ${{ secrets.DOCKER_HUB_USERNAME }}/seasonsbot:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/seasonsbot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Unraid
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UNRAID_HOST }}
        username: ${{ secrets.UNRAID_USERNAME }}
        password: ${{ secrets.UNRAID_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/seasonsbot:latest
          docker stop seasonsbot || true
          docker rm seasonsbot || true
          docker run -d --name seasonsbot \
            -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
            -e API_BASE_URL=http://dialodds-api:8080 \
            --network mynetwork \
            ${{ secrets.DOCKER_HUB_USERNAME }}/seasonsbot:latest